configuration:
  runtime: "concord-v2"
  dependencies:
    - "mvn://org.python:jython-standalone:2.7.2"

flows:
  onPush:
    - task: docker
      in:
        image: library/alpine
        cmd: |
          echo "First command"
          echo "Second command"
          echo "Third command"
          echo "Fourth command"
    - script: python
      body: |
        a = [2,3,5,7,9]
        print(a[-1])

triggers:
  - github:
      version: 2
      useInitiator: true
      entryPoint: onPush
      conditions:
        type: push
